### PR TITLE
Added prompt for hostname; polished some messages

### PR DESCRIPTION
**Pull request by RodBarnes**
Added prompt for `hostname`.  I did this in setup.sh since it should apply to all distros.
Improved message wrap and readability in several places.  No functional changes made.

### CODE REVIEW

**Comment by RodBarnes** [comment]
@MilkyDeveloper  I'm going to suggest you not accept this PR.  I just noticed an issue building arch that doesn't occur in your main.  I don't know what it is -- don't really know what I might have affected -- but, in any case, I recommend rejecting this PR.

**Comment by MilkyDeveloper** [comment]
Great PR!!! It feels very rewarding to have others contribute to your project. I’ll be taking some of your edits and add them to this project.

**Review by MilkyDeveloper — COMMENTED** [review]
Added in latest commit

**Review by MilkyDeveloper — COMMENTED** [review]
Added on latest commit

**Review by MilkyDeveloper — COMMENTED** [review]
Purging the contents of /mnt could result in possible data loss, and there’s no guarantee that the user has mounted the USB to /mnt before this. I’m going to leave this script out but document removing linux-build.

**Comment by RodBarnes** [comment]
Thanks for the feedback.  I really like what you're doing here and just want to contribute what I can to help out.  Everything is working on my ChromeBook.

The changes I made for getting the hostname doesn't work with Arch.  It was this discovery that led me to decide to scratch all of this and start with a new fork.  But since you are accepting some of this, I'll wait to see where things end up when I next check the fork before I decide to unfork/refork.  (It currently still shows as 29 commits above cb-linux.)

**Pull request closed without merging**
