### PR TITLE
Migrate to Python

### PR DESCRIPTION
**Pull request by timmypidashev**
### Status
- [ ] Ready

### Summary
A migration to a python code base. 
Supports running as a module with `python -m breath`. Another thought later long-term is to maintain PKGBUILD's of a packaged breath with for several various distributions. This would allows users to have a maintained version of breath's latest release without having to use the `master` branch for installing. This would also minimize issues since most users would be using stable versions tested to work.
* Argparse command-line parser. Currently looks a little something like this:
```
$ python -m breath -h
usage: breath [options...]

A way to natively run Linux on modern Chromebooks without replacing firmware

options:
  -h, --help                                                                  show this help message and exit
  -t, --installtype {usb,iso}                                                 choose installation type (default: usb)
  -k, --keymap                                                                map keys to chromebook actions
  -d, --distro {arch,debian,fedora,ubuntu}                                    choose distro (default: ubuntu)
  -de, --desktop {cli,gnome,kde,minimal,deepin,budgie,fce,lxqt,mate,openbox}  choose desktop environment (default: cli)
  -hn, --hostname HOSTNAME                                                    set hostname (default: chromebook)
  -u, --username USERNAME                                                     set username (default: breath_user)
  -p, --password PASSWORD                                                     set password (default: breath_passwd)
  -sp, --systempasswd SYSTEMPASSWD                                            input system password for root access, needed to run breath!
  -vv, --verbose                                                              set installer output to verbose
  -v, --version                                                               output version information and exit
```
The command-line args are put into a dictionary: `installation_options`. Default looks a little something like this:
```bash
{'installtype': 'usb', 'keymap': False, 'distro': 'ubuntu', 'desktop': 'cli', 'hostname': 'chromebook', 'username': 'breath_user', 'password': 'breath_passwd', 'systempasswd': None, 'verbose': None, 'version': False}
```
This allows for a input-less installation, as all necessary features/settings are configured in one command. This, however, may get tedious and rather large, which is why the installer will ask all necessary input questions along with the toilet flare if no args are supplied.
* Finally, ease of development. Using separate files for different common installation steps while managing everything in __init__ is a very simple and common way to make python packages. The benefit at the end is the code base will be very similar in structure to the current one, while also being extremely simple to expand.

### Tasks
- [x] Add argparse parser
- [x] Add user input menu(inquirer)
- [x] Add exception/error handler(errors.py)
- [x] Add system abstraction(system.py)
- [ ] Add keymap feature
- [ ] Add distributions support
- [ ] Add desktop support
- [ ] Add proper typehinting
- [ ] Add support for Apple
- [ ] Update this tasklist as developed.

I know this is a pretty hefty pr, and I also really don't have much time on my hands these next few coming weeks due to school, but I will do my best to continue working. It isn't as important as fixing up audio issues, bootloader, etc., but hopefully once all that is done we can make a nice repo that is maintainable longterm. @MilkyDeveloper please let me know if this is the direction you wish to take the repository, It's not an easy answer so take your time. If you like it but feel there are certain directions you wish to take differently, by all means let me know, I have opened access to maintainers for that very reason.

### CODE REVIEW

**Comment by MilkyDeveloper** [comment]
Wow!!! This is great. Once we have an initial Python branch, we can use transpilers like Js2Py, Rusthon, Grumpy, and py2many. I completely understand about slower work, I'm also slowing my work on this specific repo (I'm shifting focuses to cb-linux/bootloader). I think this is a good direction; once we have python as our base language, we can use transpilers or manually adapt to other languages.

Again, Huge thanks!!! No pressure, I completely understand school stuff.

**Comment by timmypidashev** [comment]
@MilkyDeveloper Alright sounds good. Take your time, for now this branch really needs no rush, as it's not the main focus. I'll continue working on it several commits a week until its complete. From there we can keep going!

**Comment by timmypidashev** [comment]
I have been trying to keep external libraries to a minimum(currently only using `argparse`, `platform`, `distro`, and  `inquirer`), but I have to admit sometimes using a library is more efficient and simple if it does exactly what you want it to do without a hassle.
```python
questions = [
            inquirer.List('install_type',
                message='Installation type',
                choices=['usb', 'iso'],
                default=defaults['install_type'],
            ),
            inquirer.List('distro',
                message='Distro of choice',
                choices=['arch', 'debian', 'fedora', 'ubuntu'],
                default=defaults['distro'],
            ),
            inquirer.List('desktop',
                message='Desktop environment',
                choices=['cli', 'gnome', 'kde', 'minimal', 'deepin', 'budgie', 'xfce', 'lxqt', 'mate', 'openbox'],
                default=defaults['desktop'],
            ),
            inquirer.Text('hostname',
                message='Breath Hostname',
                validate=lambda _, x: re.match('(?:^|\\s)[a-z]+(?:\\s|$)', x),
                default=defaults['hostname'],
            ),
            inquirer.Text('username',
                message='Breath Username',
                validate=lambda _, x: re.match('(?:^|\\s)[a-z]+(?:\\s|$)', x),
                default=defaults['username'],
            ),
            inquirer.Password('password',
                message='Breath Password',
                validate=lambda _, x: re.match('^\S+$', x),
            ),
            inquirer.Password('system_passwd',
                message=f'Root password for {os.getlogin()}',
                validate=lambda _, x: re.match('^\S+$', x),
            ),
            inquirer.Confirm('keymap',
                message='Map keys to chromebook actions?',
                default=True,
            ),
            inquirer.Confirm('verbose',
                message='Set verbose installation output?',
                default=True,
            ),
        ]

        user_input = inquirer.prompt(questions, theme=BreathInquirerTheme())
```
image

**Comment by timmypidashev** [comment]
@MilkyDeveloper No problem :) The idea is basically: argparse for speedy install options, inquirer for first time installations.
Everything is put into a dictionary, which is modified along the way based on whatever the user is doing, then passed on to the installer. So far I'm liking how its working.

**Comment by timmypidashev** [comment]
Alrighty where pr #133 failed with password autoprompts, the subprocess module has fixed quite elegantly as of 7ba64ca

**Comment by timmypidashev** [comment]
Turns out 'system_passwd' isn't needed as the run_root_cmd() will cache the root passwd in stdin, which means a password prompt for root only shows up once.

**Comment by timmypidashev** [comment]
@ArtemPozharov Windows and Darwin systems are not currently supported, though I have already added checks for both unsupported platforms(see [system.py](https://github.com/timmypidashev/breath/blob/port/python/breath/system.py)), so supporting them is just a matter of trial and error, but I'm confident it can be done.

**Comment by MilkyDeveloper** [comment]
Bash even runs on Windows/MacOS. The main issue is partitioned drives and running chroot, the latter of which is just impossible. We already have Crostini support, so I think it would be feasible to exclude cross platform support for Windows. This could easily be dockerized, though.

**Comment by timmypidashev** [comment]
@MilkyDeveloper I didn't know about Windows not supporting chroot. This makes sense though, I suggest we just point Windows users to create a virtual Ubuntu install on Windows if they really can't use another os.

**Comment by MilkyDeveloper** [comment]
I think WSL2 would work well too. Windows 11 and 10 Insider has direct USB passthrough.

**Comment by MilkyDeveloper** [comment]
Also, when you get to the more complicated logic in utils/download.sh, you could look in my incomplete Powershell (Linux version) port.

**Comment by timmypidashev** [comment]
> Also, when you get to the more complicated logic in utils/download.sh, you could look in my incomplete Powershell (Linux version) port.
Will do :)

**Comment by timmypidashev** [comment]
> I think WSL2 would work well too. Windows 11 and 10 Insider has direct USB passthrough.

Depending on what the user installs, wsl would probably be the best option for a Windows user without breath having to do any extra logic.

**Comment by MilkyDeveloper** [comment]
Nice progress. You could use the python library [Plumbum](https://medium.com/@zwinny/writing-shell-scripts-in-python-with-a-funny-lib-plumbum-777dddc82bfa) if you like the syntax.

**Comment by timmypidashev** [comment]
@MilkyDeveloper Thanks, I will. What I'm finding is that most commands that need to be run are better off when abstracted by python pre-configured functions that can catch errors, etc. In terms of the current progress, what I'm probably going to do is create static methods for the installer and figure it all out like a scratchpad, then sort and restructure to match something along the likes of BreathSystem, because quite honestly BreathInstaller is becoming a mess.

**Comment by timmypidashev** [comment]
Ooh plumbum seems to have it all in terms of shell scripting. I think this is a good idea, thanks for the suggestion.

**Comment by timmypidashev** [comment]
Plumbum also provides easy color access, which eliminates the need for cprint and the like. Overall it seems like a great library to build breath up with. I'm going to give it a try and see how it goes.

**Comment by timmypidashev** [comment]
I'm going to close this pr as it has gotten quite tedious trying to get a CLI interface and use the core of breath. I have found it even more frustrating to keep an elegant standard as there really is no proper way to maintain Python and Bash scripts together. Will keep looking for a solution in my spare time however.

**Pull request closed without merging**
