### PR TITLE
[enh] Rewrite of audio system

### PR DESCRIPTION
**Pull request by runcros**
Hello, this is an enhancement for audio configuration system.

You can configure all board with `breath-audio nami` as nami is the board name.

- Internal speaker is working, microphone needs some fixes, hdmi needs further testing/enhancement. (for lars - sklnau8825max))
- Pipewire experimental support also added.

Note: kernel update message has been changed to avoid repetitions at the end of the script

Testing status : 
- lars is working as expected (ubuntu-gnome)

Commits to-do:
- Pipewire full support (only display available sound etc)
- HDMI support
- Audio jack support 
- Microphone support

Status of the pull request : NOT READY TO BE MERGED

### CODE REVIEW

**Comment by MilkyDeveloper** [comment]
I’ll review this PR once I get home. Everything looks good, but I would rather keep all the changes in `setup-audio`.

**Comment by runcros** [comment]
I separate the two file because I will update it progressively to make pipewire working in futur I will also in future do a pr to rework the audio setup process.

During this rework I need the file to be separate just to be sure not forget essential part of any file.

**Comment by runcros** [comment]
I think we need more tester because not people on skylake have sklnau8825max.

And the setup-audio works only in certain case and setup-audio-skl work for another cases so I think we need to have enough tester. Meanwhile the two files should remain separate.

**Comment by runcros** [comment]
This should be ready to merged.

**Comment by runcros** [comment]
Added support of pipewire natively, created all-in-one script for configuring audio (usage `breath-audio nami` as nami is the board name`)

**Comment by runcros** [comment]
The AIO works in lars.

**Pull request closed without merging**
