### PR TITLE
WIP: debian improvements

### PR DESCRIPTION
**Pull request by hede5562**
I'm working on some improvements regarding debian and probably some general fixes. For example to choose the release like with ubuntu. 
My chromebook uses special keycodes for the function keys ontop of the numeric row. As I'm using Gnome/Wayland here the old way of using xkb overlays doesn't work so I created some second layout (currently for "de" only) and added an option to re-assign some keys (like the lock-key as "delete" and "insert" key). 

 This is all work-in-progress but maybe you want to take a look into it to make your comments in this early stage. 

Probably you won't accept most of the commits but I have split my patches into single commits to make it easier to select some of them individualy.

### CODE REVIEW

**Review by MilkyDeveloper — COMMENTED** [review]
The Crostini mkdir still applies; Crostini is supported but not documented yet.

**Comment by MilkyDeveloper** [comment]
For fatal errors, I already have this implemented in scripts where it is necessary.

**Comment by MilkyDeveloper** [comment]
We have some package errors when using Debian stable. I’ll could set it to $DISTRO_VERSION, though.

**Comment by MilkyDeveloper** [comment]
Everything else looks amazing though! Thanks.

**Comment by hede5562** [comment]
> The Crostini mkdir still applies; Crostini is supported but not documented yet.

Yes, but the mkdir is redundant, that means it exists at two places. I noticed this because of the "set -e" thing.

**Comment by hede5562** [comment]
> Everything else looks amazing though! Thanks.

Thank YOU  for the this project  :)

> We have some package errors when using Debian stable.

I'm using debian stable, that was the reason for changing it for me in the first place. What kind of package errors do you mean? (in case you remember)

**Comment by hede5562** [comment]
Regarding the "work-in-progress" state: A draft request means you won't review even the good parts. So I made a non-draft one.

I thought maybe you want to cherry-pick useful commits like described there: https://stackoverflow.com/questions/7217031/github-accept-pull-request-but-only-some-commits

Then closing the request, rejecting those parts you don't like.

**Comment by hede5562** [comment]
The keyboard part seems to be special to my device; maybe I should separate this into its own branch.

**Pull request closed without merging**
