### PR TITLE
Support building on Arch-based systems

### PR DESCRIPTION
**Pull request by timmypidashev**
### Status
- [x] Ready

### Summary
The current state of the project is that it can only be used on Debian-based distros. Adding an OS abstraction and proper support for distributions such as Arch Linux will greatly increase the reach of the project. On top of this, further distro's can be easily supported afterwards, possibly MacOS as well if needed.

### Tasks
- [x] Arch support
- [x] Fedora support
- [x] Per-Distro dependency abstraction
- [x] Update docs
- [x] Initial approval

### CODE REVIEW

**Comment by timmypidashev** [comment]
Early work in progress. I'm also a bit busy but I will try and get it complete asap if its something desired :)

**Comment by timmypidashev** [comment]
Running makepkg as root is not allowed, and simply running the command under `su` fails as well. Defaulted to letting the user install.

**Comment by MilkyDeveloper** [comment]
This is some really clean code. I'll be adding some PRs to your fork (before merging) if you don't mind.

**Comment by timmypidashev** [comment]
One thing I haven't quite figured out yet is per-system dependency management, as package names can vary per system. 
For example:
`vboot-kernel-utils` ~ debian; `vboot-utils` ~ arch
One way to go about this would be to catch the error, and then check what dep and install, but this will be quite bloated in the long run...

**Comment by MilkyDeveloper** [comment]
What I would do is pass something like `installDependencies vboot-kernel-utils`, and `installDependencies` has an if statement that would work something like this (psuedocode):
```
PACKAGE=$* # Will be overriden if using a special package, I don't think we can set $*

if [[ $* == "vboot-kernel-utils" ]]; then
    case DISTRO in 
      Debian)
        PACKAGE=vboot-kernel-utils
      Arch)
        PACKAGE=vboot-utils
fi
```

**Comment by timmypidashev** [comment]
@MilkyDeveloper That's pretty smart, that's what I'll do

**Comment by timmypidashev** [comment]
Found a better solution
```bash
for var in "$@"
do
    case $var in 
    
    # vboot-utils
    vboot-kernel-utils)
        var=vboot-utils;
    
    esac
    yay -S --noconfirm var
done
```
Essentially instead of overriding `$*`, we would loop through all arguments and replace the ones that aren't correct.

**Comment by MilkyDeveloper** [comment]
Oh yeah, that looks better. Nice one.

**Comment by timmypidashev** [comment]
Ok now the biggest problem is running yay as sudo will cause problems. The most notable of which now is happening when trying to install vboot-utils:
```bash
:: (0/1) Downloaded PKGBUILD: vboot-utils
 -> error fetching vboot-utils: fatal: could not create work tree dir 'vboot-utils': Permission denied 
	 context: exit status 128
```
I'm not exactly sure how to go about doing this, I've tried adding a command in `functions.sh` unsucessfully. Will keep researching, there should be a way to drop root priveleges for this.

**Comment by MilkyDeveloper** [comment]
Are you running `setup.sh` as root? That could be the cause for it, try running it as a normal user.

**Comment by timmypidashev** [comment]
Yes I am. Isn't the script required to run as root though?

**Comment by timmypidashev** [comment]
Ok running some tests to make sure everything works :)

**Comment by timmypidashev** [comment]
Alrighty everything is working as expected! @MilkyDeveloper you did note you were going to merge something into this branch as well, so I'll call my work done from here for now and let you take over :)
image

**Comment by timmypidashev** [comment]
Im going to add fedora support if I have enough time today, will test in a vm.

**Comment by timmypidashev** [comment]
Alright Fedora support is working, but just like arch `vboot-kernel-utils` and `cgpt` require some edits. Will finish tomorrow.

**Comment by MilkyDeveloper** [comment]
Nice, huuge thanks for this. Could I merge this PR? I'll be updating the docs.

**Comment by timmypidashev** [comment]
@MilkyDeveloper feel free, just finished up :)

**Comment by timmypidashev** [comment]
One thing to note though, the iso installation wasn't touched, and as such will only work on debian. An oversight on my part, but can be fairly easy fix if you need that.

**Comment by timmypidashev** [comment]
Yes expand.sh, and alright good luck :+1:

**Pull request merged**
